const GET_SECTION = 'GET_SECTION';
const CHANGE_FILTER = 'CHANGE_FILTER';
const GET_BY_CATEGORY = 'GET_BY_CATEGORY';
const GET_BY_INGREDIENT = 'GET_BY_INGREDIENT';
const GET_MEAL_BY_ID = 'GET_MEAL_BY_ID';
const GET_ERROR = 'GET_ERROR';

export {
  GET_SECTION,
  CHANGE_FILTER,
  GET_BY_CATEGORY,
  GET_BY_INGREDIENT,
  GET_MEAL_BY_ID,
  GET_ERROR,
};
