const GET_CATEGORIES = 'GET_CATEGORIES';
const GET_COUNTRIES = 'GET_COUNTRIES';
const GET_INGREDIENTS = 'GET_INGREDIENTS';
const GET_BY_CATEGORIES = 'GET_BY_CATEGORIES';
const GET_BY_COUNTRIES = 'GET_BY_COUNTRIES';
const GET_BY_INGREDIENTS = 'GET_INGREDIENTS';

export {
  GET_CATEGORIES,
  GET_COUNTRIES,
  GET_INGREDIENTS,
  GET_BY_CATEGORIES,
  GET_BY_COUNTRIES,
  GET_BY_INGREDIENTS,
};
